# Generated by Django 3.2.6 on 2021-08-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_auto_20210825_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplane',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
