# Generated by Django 3.2.6 on 2021-08-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_alter_airplane_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplane',
            name='code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
